
version: "2.3"
services:
  jigsaw:
    image: jigsaw:0.0.2
    container_name: jigsaw-${USER}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TORCH_CUDA_ARCH_LIST: ${TORCH_CUDA_ARCH_LIST}
        DETECTRON2_VERSION: ${DETECTRON2_VERSION}
    command: /bin/bash
    runtime: nvidia
    shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ../:/jigsaw
      - /dataset:/dataset
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - TERM=$TERM
    tty: true
