program_param:
  wandb_key: 
  project_name: jigsaw
  seed: 42

data_param:
  dir_name: jigsaw-toxic-severity-rating
  train_file_name: added_data.csv
  infer_file_name: comments_to_score.csv
  valid_file_name: toxic_task.csv
  do_score_check: False

model_param:
  model_name: gpt2
  max_length: 128
  scheduler: cos_ann_warm
  mix_precision: True
  num_classes: 1
  device: cuda
  drop_p: 0.2
  is_extra_attn: True
  is_deeper_attn: True
  level_list: [-1,-2,-4]

train_param:
  epochs: 4
  lr: 1e-4
  min_lr: 1e-6
  weight_decay: 1e-6
  num_folds: 5
  accumulate_grad_batches: 3
  ranking_margin: 0.5
  batch_size: 16
  T_max: 500
  T_0: 50
  save_dir: checkpoint/gpt2
  loss: margin_ranking_loss
  num_workers: 6
  shuffle: True
  pin_memory: True
  drop_last: True

valid_param:
  batch_size: 64
  num_workers: 6
  shuffle: False
  pin_memory: True
  
infer_param:
  batch_size: 64
  num_workers: 6
  shuffle: False
  pin_memory: True
  checkpoint_path: checkpoint/gpt2/gpt2.bin
  save_dir: /jigsaw/output/gpt2
